# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: blog_dev
  host: 127.0.0.1
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: blog_test
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: blog
  host: 127.0.0.1
  pool: 5
  timeout: 5000
