# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a15f0ae5a94afad256ea2c09b35c6556bf2b1627c3d0f04fbba06eac4bff5dc3ec2ec7b87faeecc09528c79fe2392e51276326971b3e4c90c8c22fb3a30e47c7

test:
  secret_key_base: d6ec989a172a54318b0b43984f02ce145241c7f37a38244d598fe08565596953c68888196b0137dd8d2c6ac00e77e9c93dfaac3f7033304515553cdd2f56a58d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
